/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ManaDatuBazeJava;

import javax.swing.JFrame;
import javax.swing.WindowConstants;

/**
 *
 * @author PUBLIC
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_Skolnieki = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Skolotaji = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem_Prieksmeti = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1012, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 444, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(255, 255, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jMenu1.setBackground(new java.awt.Color(153, 153, 153));
        jMenu1.setText("Manage");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        jMenuItem_Skolnieki.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_Skolnieki.setText("Skolnieki");
        jMenuItem_Skolnieki.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SkolniekiActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Skolnieki);
        jMenu1.add(jSeparator1);

        jMenuItem_Skolotaji.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_Skolotaji.setText("Skolotāji");
        jMenuItem_Skolotaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_SkolotajiActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Skolotaji);
        jMenu1.add(jSeparator2);

        jMenuItem_Prieksmeti.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItem_Prieksmeti.setText("Priekšmeti");
        jMenuItem_Prieksmeti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_PrieksmetiActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_Prieksmeti);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_PrieksmetiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_PrieksmetiActionPerformed
        
        //open the manage Skolnieki form
        ManagePrieksmetiForm PrieksmetiForm = new ManagePrieksmetiForm();
        PrieksmetiForm.setVisible(true);
        PrieksmetiForm.pack();
        PrieksmetiForm.setLocationRelativeTo(null);
        PrieksmetiForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItem_PrieksmetiActionPerformed

    private void jMenuItem_SkolniekiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SkolniekiActionPerformed
         
        //open the manage Skolnieki form
        ManageSkolniekiForm SkolniekiForm = new ManageSkolniekiForm();
        SkolniekiForm.setVisible(true);
        SkolniekiForm.pack();
        SkolniekiForm.setLocationRelativeTo(null);
        SkolniekiForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                
    }//GEN-LAST:event_jMenuItem_SkolniekiActionPerformed

    private void jMenuItem_SkolotajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_SkolotajiActionPerformed
        
        //open the manage Skolnieki form
        ManageSkolotajiForm SkolotajiForm = new ManageSkolotajiForm();
        SkolotajiForm.setVisible(true);
        SkolotajiForm.pack();
        SkolotajiForm.setLocationRelativeTo(null);
        SkolotajiForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
    }//GEN-LAST:event_jMenuItem_SkolotajiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_Prieksmeti;
    private javax.swing.JMenuItem jMenuItem_Skolnieki;
    private javax.swing.JMenuItem jMenuItem_Skolotaji;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
